apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-development
  labels:
    app: app-development
spec:
  selector:
    matchLabels:
      app: app-development
  template:
    metadata:
      labels:
        app: app-development
    spec:
      containers:
        - name: app-container
          image: gymfit/dev-gitaction-demo:latest
          ports:
            - containerPort: 8081
          resources:
            requests:
              cpu: "100m"   # CPU 요청을 100m (0.1 CPU)로 설정
            limits:
              cpu: "150m"   # CPU 제한을 200m (0.2 CPU)로 설정
              memory: "256Mi"  # 메모리 제한을 256Mi로 설정
      imagePullSecrets:
        - name: dockerhub-secret
---
apiVersion: v1
kind: Service
metadata:
  name: app-service-development
spec:
  type: NodePort
  selector:
    app: app-development
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
      nodePort: 30090

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: app-autoscaler-development
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: app-development
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
